// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtenrjmtqyiwevajzzoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0ZW5yam10cXlpd2V2YWp6em9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MzQyNjMsImV4cCI6MjA3MzAxMDI2M30.kjxXvON_Vz-sHW20UqlUYh2aL46gFsTA2rJTdsIUAuk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});